### PR TITLE
Dynamic Event Registration

### PR DESCRIPTION
**Pull request by da-h**
# Dynamic Event Registration
This PR enables any event to itself append to existing events or even overwriting existing events.

To accomplish this, this PR does the following:
- `mf` (the same object as is used during `register(mf)` to the list of possible arguments that are automatically determined and passed to an event upon execution
- `mf.overwrite_event` to redefine previous definitions completely
- `mf.register_event` clears the cache of the `event`-object automatically
- adds a simple test case for event registration during an event

### CODE REVIEW

**Review by sbrodehl — COMMENTED** [review]
Here is my feedback:
- Is the `mf` variable automatically added as an argument like `state` and `event`?
- How can one `unregister` an event?

**Comment by da-h** [comment]
- correct `mf` is an optional, automatically passed argument as `state` and `event`
- is un-registration a desired feature? if so, it would be easy to make the api public. The function is already present in this PR.

**Comment by sbrodehl** [comment]
I think un-registration might come in handy.

**Comment by da-h** [comment]
> I think un-registration might come in handy.

Done.

**Review by sbrodehl — APPROVED** [review]

**Pull request merged**
